language: python
os:
- linux
install: true
script: python tests.py
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make funscripting.zip; fi
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: KSZ2x9H2IjPTeJ2rMxT3JNkXMyXWI9Li55hbY1EhFde2ZDidiWWKpSUcVAS9NhuOEvcdlUjoOqxp73zsjXyYGQuEWbaBbjxY8/AXd9LZ8f+os84j7YtbfDueI+vQ7kuHLYHuE9wdpgSRYB5211jvBbcRvMI/Kyko2yfCpmoM4MIPj7pSXULOLRFTMpap0yokRxBTFyQcKnb+c2CgFFjlOpBF3ZYyxlOkPAWrCNa3ax9s89Sb339aUIR9D4Cs850tDWE3W3+1ITryEgpDRRgJ6epsPhlsOdvxRs8CkZD1M3r0vIqxLNiJY3k/hSKITKgKGF/PrGHtxgRjdYmpk+i9EdeoHruExS8wAj2mMnkYdaGrqsHLq/zrE2t+oxmrd9UWe/MxxGozm5ntGfOkJxN1feY93Foh1sBR5dBa5C1SnAebaeXTvNZBxfCA1PMUncLmd1dL+Bd1z9XV1LANPnEKV6Gra1wUp6Q0DXvpjKfPG7QudVkohc/CbgmFA07gw3NKcBsK4/S4S8oUVoCBEK2tGM+HLO5p6Myq3UVQiZt6016g2M0is5fqfc52i0JCguP4PUXcKN64NGvIwqi0AJUa7w6HlR04M/jAvwiHEZ+UHFnFeacmRHPl4dwaZXjNW/6PBC8dh9M/sXaZUPDKG1XUcs5SNBPnpfIt7t0Ud+6nuUk=
  file:
  - funscripting.zip
  - contrib/Funscripting.blend
  on:
    tags: true
    repo: funjack/funscripting
    branch: "master"
    condition: $TRAVIS_OS_NAME = linux
